/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ForGradsRouteImport } from './routes/for-grads'
import { Route as IndexRouteImport } from './routes/index'

const ForGradsRoute = ForGradsRouteImport.update({
  id: '/for-grads',
  path: '/for-grads',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/for-grads': typeof ForGradsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/for-grads': typeof ForGradsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/for-grads': typeof ForGradsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/for-grads'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/for-grads'
  id: '__root__' | '/' | '/for-grads'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ForGradsRoute: typeof ForGradsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/for-grads': {
      id: '/for-grads'
      path: '/for-grads'
      fullPath: '/for-grads'
      preLoaderRoute: typeof ForGradsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ForGradsRoute: ForGradsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
