/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ModalTestRouteImport } from './routes/modal-test'
import { Route as ForProfessionalsRouteImport } from './routes/for-professionals'
import { Route as ForGradsRouteImport } from './routes/for-grads'
import { Route as BareTestRouteImport } from './routes/bare-test'
import { Route as IndexRouteImport } from './routes/index'

const ModalTestRoute = ModalTestRouteImport.update({
  id: '/modal-test',
  path: '/modal-test',
  getParentRoute: () => rootRouteImport,
} as any)
const ForProfessionalsRoute = ForProfessionalsRouteImport.update({
  id: '/for-professionals',
  path: '/for-professionals',
  getParentRoute: () => rootRouteImport,
} as any)
const ForGradsRoute = ForGradsRouteImport.update({
  id: '/for-grads',
  path: '/for-grads',
  getParentRoute: () => rootRouteImport,
} as any)
const BareTestRoute = BareTestRouteImport.update({
  id: '/bare-test',
  path: '/bare-test',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bare-test': typeof BareTestRoute
  '/for-grads': typeof ForGradsRoute
  '/for-professionals': typeof ForProfessionalsRoute
  '/modal-test': typeof ModalTestRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bare-test': typeof BareTestRoute
  '/for-grads': typeof ForGradsRoute
  '/for-professionals': typeof ForProfessionalsRoute
  '/modal-test': typeof ModalTestRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bare-test': typeof BareTestRoute
  '/for-grads': typeof ForGradsRoute
  '/for-professionals': typeof ForProfessionalsRoute
  '/modal-test': typeof ModalTestRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/bare-test'
    | '/for-grads'
    | '/for-professionals'
    | '/modal-test'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/bare-test' | '/for-grads' | '/for-professionals' | '/modal-test'
  id:
    | '__root__'
    | '/'
    | '/bare-test'
    | '/for-grads'
    | '/for-professionals'
    | '/modal-test'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BareTestRoute: typeof BareTestRoute
  ForGradsRoute: typeof ForGradsRoute
  ForProfessionalsRoute: typeof ForProfessionalsRoute
  ModalTestRoute: typeof ModalTestRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/modal-test': {
      id: '/modal-test'
      path: '/modal-test'
      fullPath: '/modal-test'
      preLoaderRoute: typeof ModalTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/for-professionals': {
      id: '/for-professionals'
      path: '/for-professionals'
      fullPath: '/for-professionals'
      preLoaderRoute: typeof ForProfessionalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/for-grads': {
      id: '/for-grads'
      path: '/for-grads'
      fullPath: '/for-grads'
      preLoaderRoute: typeof ForGradsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bare-test': {
      id: '/bare-test'
      path: '/bare-test'
      fullPath: '/bare-test'
      preLoaderRoute: typeof BareTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BareTestRoute: BareTestRoute,
  ForGradsRoute: ForGradsRoute,
  ForProfessionalsRoute: ForProfessionalsRoute,
  ModalTestRoute: ModalTestRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
